parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: tsm
    database_user: tsmontag
    database_password: tsmontag
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: ts-montag
    mailer_password: ts-montag
    locale: en
    secret: 0ffd00a46f335515afa548f8fbf33c4b0a9278b1
    database_path: null
