tsm_catalog:
    resource: "@TsmCatalogBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_static_contacts:
    defaults: { _controller: TsmCatalogBundle:StaticPageRest:getContacts }
    pattern: /contacts

_static_partners:
    defaults: { _controller: TsmCatalogBundle:StaticPageRest:partners }
    pattern: /partners

_static_about:
    defaults: { _controller: TsmCatalogBundle:StaticPageRest:about }
    pattern:  /about

_static_feedback:
    defaults: { _controller: TsmCatalogBundle:Feedback:contact }
    pattern:  /feedback
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
