Catalog:
    type: entity
    table: catalog
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
        descr:
            type: string
            length: 1024
            fixed: false
            nullable: false
        price:
            type: integer
            unsigned: false
            nullable: false
        category:
            type: integer
            unsigned: false
            nullable: false
        parent:
            type: integer
            unsigned: false
            nullable: false
    lifecycleCallbacks: {  }
