MigrationVersions:
    type: entity
    table: migration_versions
    fields:
        version:
            id: true
            type: string
            length: 255
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
